### ISSUE TITLE
make attaching of a disk work 

### ISSUE THREAD

**Issue by rgevaert** [gig-tech/ovc-disk-csi-driver#4]
Currently a disk can not be attached because there is no generic way to identify the virtual machine.

 `Warning  FailedAttachVolume  5m9s (x5046 over 7d3h)   attachdetach-controller           AttachVolume.Attach failed for volume "pvc-10e5e55f-6747-11e9-a98a-525400001541" : rpc error: code = Unknown desc = "Could not find 0 of type vmachine"`

The `id` is parsed from the hostname (here `worker-0-be-gnt-dc01-01`)

See https://git.gig.tech/openvcloud/openvcloud/issues/2236 for a way to handle it in the openvcloud API.

Have a look at this comment too, https://github.com/kubernetes/kubernetes/issues/58927#issuecomment-361325954

**Comment by chrisvdg** [comment]
Added in https://github.com/gig-tech/ovc-disk-csi-driver/commit/8ed549d8b298420cedd53eaf0a19ee9af0ad7372
